### ISSUE TITLE
replace the ugly loading jpeg with some nice svg loaders

### ISSUE THREAD

**Issue by lmssieh** [Aevann1/rDrama#136]
some examples: https://github.com/SamHerbert/SVG-Loaders

**Comment by lmssieh** [comment]
https://i.imgur.com/qL4pmi9.png

I'm talking about this one, it looks very ugly especially with other themes.

**Comment by UnironicHeyMoon** [comment]
First drunk driving, then freestyle peeing. What's next?

**Comment by bintrac** [comment]
think svgs require dependencies but here's a nice gif: 
 https://upload.wikimedia.org/wikipedia/commons/b/b9/Youtube_loading_symbol_1_(wobbly).gif

**Comment by lmssieh** [comment]
closing, since looks like loading image has been changed.
