### ISSUE TITLE
Embed all the links!

### ISSUE THREAD

**Issue by ghost** [Aevann1/rDrama#222]
It would be nice to be able to embed more types of links, like:

- Soundcloud
- Raw audio/video files (e.g. `https://files.catbox.moe/svddz9.mp3`). Also you can embed other types of files like PDFs using `<object>`.
- Peertube links (might require crawling the page with `curl` to check if it's a peertube site, or having a specific syntax for embedding peertube videos, or having a pre-approved list of domains or something like that). [stuff](https://thinkmoult.com/embed-peertube-video-on-your-website.html)
- Vimeo
- Bittorrent magnet links (these currently get butchered by emoji dectection, for example `magnet:?xt=urn:btih:5e7886d42a52ae66da4541d88882a04f9a34a649` gets broken because it thinks `:btih:` is an emoji).

**Comment by ethark** [comment]
This isn't urgent or something. If anyone can think of any other URLs that should be embedded, list them here.

**Comment by guyonabuffallo** [comment]
Vocaroo is popular. Probably would be a nice add.

**Comment by Aevann1** [comment]
no i dont think i will
