### ISSUE TITLE
Some animated emoji are glitched on iOS

### ISSUE THREAD

**Issue by float-trip** [Aevann1/rDrama#254]
![clapping](https://user-images.githubusercontent.com/102226344/167305094-f1013d20-934e-4a41-bb56-04990a2d6187.gif)

This is a bug in how WebKit renders transparent webp's: https://bugs.webkit.org/show_bug.cgi?id=217897

I don't expect it'll get fixed anytime soon, just making this issue so others don't waste time looking into it

**Comment by Aevann1** [comment]
seems the bug got fixed
