### ISSUE TITLE
Cloudflare blocking text posts with attached images

### ISSUE THREAD

**Issue by guyonabuffallo** [Aevann1/rDrama#284]
Tried with vpn on. Disabled it. Text post will submit but if an image is attached it's blocked.

CalyxOS 3.4 android 12. Kiwi browser.

![Screenshot_20220523-155536_1](https://user-images.githubusercontent.com/85253001/169975931-794f9482-8a48-47a2-9d74-d2f297764a02.png)

**Comment by DrTransmisia** [comment]
What's the image?

**Comment by guyonabuffallo** [comment]
![Uploading PXL_20220523_184102784.jpg…]()

**Comment by guyonabuffallo** [comment]
![PXL_20220523_184102784](https://user-images.githubusercontent.com/85253001/170154742-2d0e73e1-be59-4d44-b61e-88407b292d19.jpg)

**Comment by justcool393** [comment]
is this still an issue?
