### ISSUE TITLE
Posts voting illuminated despite not even viewing or up voting post

### ISSUE THREAD

**Issue by guyonabuffallo** [Aevann1/rDrama#292]
![Screenshot_20220529-203144_1](https://user-images.githubusercontent.com/85253001/170912403-3aa89778-564f-413c-8fd9-9e16bcd64171.png)
![Screenshot_20220529-203117_1](https://user-images.githubusercontent.com/85253001/170912405-8c41dc40-fcd3-4d84-886f-357ad0d556d1.png)
As the subject suggests, some posts indicate they were upvoted despite never being upvoted. I was checking out

https://rdrama.net/@JoeBiden

To see what he has been posting and noticed what is indicated in my screenshots. This is using the mobile website on Android 12 and kiwi browser.

I understand the issue where you can up vote and undo your vote and have the number be illuminated but this is a different scenario (no voting occurred).

**Comment by TLSM** [comment]
NOTABUG. That's the controversial coloring:

https://github.com/Aevann1/rDrama/blob/frost/files/assets/css/main.css#L4631-L4634

(thanks for the detailed report, though)
