### ISSUE TITLE
Make 429 page plaintext or JSON

### ISSUE THREAD

**Issue by nekobbbbbbit** [Aevann1/rDrama#303]
Spitting back a large fancy HTML page with lots of content defeats the purpose of a "Too many requests" page.

SQL still gets ran because it pings for the logged in user as well and other various bits of info.

Also lower it for logged in users?

**Comment by justcool393** [comment]
we don't ping for the logged in user anymore
lemme know if this is still an issue and i can reopen it
ty <3
