### ISSUE TITLE
Schizo lives matter prompt truncated 

### ISSUE THREAD

**Issue by guyonabuffallo** [Aevann1/rDrama#314]
On mobile (kiwi browser Android 12) in at least the schizo hole the prompt notifying users of the required text is truncated and the only way to see what the issue is is to enable desktop mode to see the whole message. See attached screenshot. 
![Screenshot_20220706-154456_1](https://user-images.githubusercontent.com/85253001/177655692-ff2a2df8-971a-4b48-9419-b7118f6d04a6.png)

**Comment by geese-suck** [comment]
It's intentional, there's no way for the entire phrase to be readable on mobile so it's just clipped instead of trying to shrink it.

**Comment by geese-suck** [comment]
Also congrats on having the first issue in rDrama history to actually get a response and not just sit there for 8 months lol

**Comment by DrTransmisia** [comment]
Fake news,  #304 got fast replies too
