### ISSUE TITLE
No prompt for attachment limit 

### ISSUE THREAD

**Issue by guyonabuffallo** [Aevann1/rDrama#315]
Appears that there's a four image or otherwise limit to an attachment for a comment /reply. Additional files are discarded without any notification or prompt.

**Comment by TLSM** [comment]
https://github.com/Aevann1/rDrama/blob/ed5e7a6187259c1cdb790c0b532c571122567209/files/helpers/media.py#L16

I recall this being discussed before. I'm under the impression the four file limit is to reduce risk of DoS by uploading a ton of files, or something. At the very least I'm hesitant to change that part of it without more investigation. Would better notification in the UI be sufficient? Possibly finding some way to get the clientside file picker to not let the user pick more than four, to make the limit clearer?

**Comment by guyonabuffallo** [comment]
Ah yeah DoS is a good point. Personally I feel like a prompt clarifying the limitation would be a good idea that only marginally changes the DoS risk.
