### ISSUE TITLE
"Real" vote flag is never updated

### ISSUE THREAD

**Issue by zorbathut** [Aevann1/rDrama#322]
See https://github.com/Aevann1/rDrama/blob/frost/files/routes/votes.py#L112 .

If a user tries to make an upvote, and is banned/has default stuff/etc, then their vote is deemed Not Real and is not counted in some cases.

But this happens only if it's an upvote. Downvotes are always considered Real. And because the flag is never updated, this means a "not-real" poster can force their votes to count by simply downvoting first, thus locking in the Real flag, and *then* upvoting.

**Comment by justcool393** [comment]
upvotes and downvotes both have a positive effect on ranking but the `@is_not_permabanned` thing basically means that someone can't change their vote, so not sure what the issue here is
