### ISSUE TITLE
[Enhancement] There should be a marsey picker as an alternative to uploading a new profile picture.

### ISSUE THREAD

**Issue by booosy** [Aevann1/rDrama#342]
![image](https://user-images.githubusercontent.com/104043001/187323009-58e0b396-88fa-43bb-ac71-efef06fb5267.png)

So a "Pick Marsey" button next to "Upload" that opens up the marsey picker and when picked uploads that one as the user's new profile picture.

Assuming no one else makes this Ill work on it myself when I'm less busy

**Comment by Aevann1** [comment]
we wanna incentivize ppl to have real pfps, not marseys
