### ISSUE TITLE
only supporting gmail?

### ISSUE THREAD

**Issue by RegularID** [Aevann1/rDrama#410]
I tried using Tutanota and Outlook neither of them worked, only when I used Gmail then it worked

**Comment by justcool393** [comment]
can you check your spam folder or spam filter settings? we don't only support gmail

**Comment by RegularID** [comment]
I see, I had a _ infront of my tutanota mail and a - infront of my outlook mail, and the regex pattern doesn't seem to support it 
![image](https://user-images.githubusercontent.com/69537751/196493003-464d950e-130d-4086-952c-00c49a8ae7c2.png)

**Comment by justcool393** [comment]
glad you got it figured it out
