### ISSUE TITLE
Issues with the comment formatting buttons

### ISSUE THREAD

**Issue by LightUmbra** [Aevann1/rDrama#98]
I have a few issues with the buttons for formatting comments (circles below) that show up when you make a top level comment or a text post. I think fixing these would be really nice for us mobile plebs. 

![button example](https://user-images.githubusercontent.com/40727254/141477743-ad1e69ba-056b-40fd-9679-6df3b381ec99.jpg)

First, when you click on them and don't have anything highlighted, they should just insert the formatting characters. For example, clicking the italics button insert \*\* and putting the cursor between them.

Second, can you add a button to do links. Should pop up a menu that takes the text and the url. See an example from reddit is fun app below. 

![link menu example](https://user-images.githubusercontent.com/40727254/141478591-195a3b1a-10be-4094-98a1-a92fe2d34a53.jpg)

Third, the buttons don't show up at all when you edit a comment (works when you edit a post though) or make non top level comment (see examples below). 

![edit comment example](https://user-images.githubusercontent.com/40727254/141478967-7e758ebc-075f-4b54-8e11-d256351efc25.jpg)

![non top level comment example](https://user-images.githubusercontent.com/40727254/141478989-af910235-f09e-4869-8067-233ecd63dd2e.jpg)

If I knew anything about JS, I'd just submit a patch, but I've avoided it like the plague. Thanks for your help!

![](https://rdrama.net/assets/images/emojis/marseypanda.webp)

**Comment by Aevann1** [comment]
> Third, the buttons don't show up at all when you edit a comment (works when you edit a post though) or make non top level comment (see examples below).

fixed king
